### ISSUE TITLE
Add Support For Chromium

### ISSUE THREAD

**Issue by PantherX** [FoldingAtHome/fah-nacl-client#29]
Despite enabling the NaCl option in Chromium (in Mint 16 64-bit fully updated), I couldn't get the F@H App to run. It showed the pop-up. From my understanding, the difference between the two (https://code.google.com/p/chromium/wiki/ChromiumBrowserVsGoogleChrome) doesn't impact the NaCl feature so it should work fine.

**Comment by jcoffland** [comment]
Can you run any NaCl programs in Chromium?  This is most likely an NaCl problem and not a F@H problem.  Please reopen this issue if you are able to run other NaCl programs but not F@H.
