### ISSUE TITLE
Folding on idle (win10)

### ISSUE THREAD

**Issue by kreuzerkrieg** [FoldingAtHome/fah-nacl-client#71]
Looks like the fah client does not kick in when machine with windows 10 in idle state (no mouse/keyboard input, screensaver started) it does occur with both regular installation and service

**Comment by 7im-** [comment]
Not idle if screen saver running.  Idle when monitor goes in to power saving mode.

**Comment by jcoffland** [comment]
Is this really for the NaCl client?  The NaCl client does not monitor idle states and is not supposed to start if self when Windows becomes idle.  Perhaps you're looking for the FoldingAtHome/fah-client-pub repo.

**Comment by kreuzerkrieg** [comment]
Oh, looks like you are right. Could you move it there or should I duplicate this issue there?

**Comment by jcoffland** [comment]
Please search the fah-client-pub repo for similar issues.  If you don't find one then please open a new issue.
