### ISSUE TITLE
"pnacl module failure, fatal" on Linux

### ISSUE THREAD

**Issue by PeterDaveHello** [FoldingAtHome/fah-nacl-client#72]
Seems this client didn't support GNU/Linux distros?

Tried on Ubuntu 14.04/15.04, both not work. Or this is nacl's problem?

**Comment by jcoffland** [comment]
@PeterDaveHello, I was surprised to see you here.  We chatted recently over in the issues section of cdnjs.

It has been working on Linux.  I haven't tried with the Distros you mentioned.  Which version of Chrome are you using?  It's working in ``43.0.2357.125 (Official Build) (64-bit)`` for me.

**Comment by PeterDaveHello** [comment]
Sorry for the missing info:

> Chromium Version 43.0.2357.130 Built on Ubuntu 14.04, running on LinuxMint 17.2 (64-bit)

**Comment by PeterDaveHello** [comment]
![screenshot from 2015-08-02 01 34 58](https://cloud.githubusercontent.com/assets/3691490/9022825/bb53fe12-38b6-11e5-9b88-c80807cd8d91.png)

**Comment by jcoffland** [comment]
NaCl should be enabled by default.  Here's some info on enabling and testing NaCl https://code.google.com/p/nativeclient/wiki/NativeClientInGoogleChrome

If you click on the items in the list on the error screen you captured above, it should show you more information.

**Comment by PeterDaveHello** [comment]
It works with Google Chrome but does not work with my Chromium, but it works on my Windows, should I close this issue or leave it opened?

**Comment by sbc100** [comment]
I would close it.  Most linux distros don't build chromium with NaCl support.  This is something we (on the NaCl team) are trying to change, but its currently expected behavior.

**Comment by 7im-** [comment]
Close as a duplicate.  See #29 - Request to add Chromium support.

**Comment by PeterDaveHello** [comment]
Thanks!
