### ISSUE TITLE
PNG missing?

### ISSUE THREAD

**Issue by MC42** [FoldingAtHome/fah-nacl-client#75]
It would appear that a single image is missing, regardless of browser.

![screenshot from 2016-10-08 20-15-18](https://cloud.githubusercontent.com/assets/6531081/19216674/07d59812-8d94-11e6-9995-71578b72849c.png)

The image in question is supposed to be at `images/micro/points.png`, though it doesn't appear in the repo, leading me to believe it was supposed to be in the FAH root server at the following URL:

`folding.stanford.edu/images/micro/points.png`

Upon even further review, the entire directory (being "micro") is no longer present.  

Any help would be appreciated.

**Comment by jcoffland** [comment]
This only works in Chrome.  The image is generated on the fly by the code.

**Comment by jcoffland** [comment]
Go [here](http://folding.stanford.edu/nacl/micro) with Chrome and it should work.

**Comment by MC42** [comment]
![image](https://cloud.githubusercontent.com/assets/6531081/19269142/d2560ca4-8f86-11e6-890f-100ffad6ce1f.png)

Not quite sure, but Chrome seems to *not* be handling it like this.

**Comment by MC42** [comment]
![image](https://cloud.githubusercontent.com/assets/6531081/19269157/e263931e-8f86-11e6-8081-a85634a95495.png)

I don't believe that Chrome is handling it as such.

**Comment by jcoffland** [comment]
You're right.  I've removed this image link.
