### ISSUE TITLE
Some executables are missing

### ISSUE THREAD

**Issue by andrin-n-dream** [FoldingAtHome/fah-nacl-client#76]
Tried to fork the project and run it.
fahcore_b0-v2-c37.pexe was missing.
Adding it from http://folding.stanford.edu/nacl/fahcore_b0-v2-c37.pexe solved the problem.

Are we not supposed to fork and run it?

**Comment by jcoffland** [comment]
You can fork and run the project but the simulation core is not Open-Source and so not part of this project.
