### ISSUE TITLE
Broken links to the old website URLs

### ISSUE THREAD

**Issue by jcoffland** [FoldingAtHome/fah-nacl-client#79]
There are a few broken links on the nacl client page (http://fahwebx.stanford.edu/nacl/).
When you click on "Team" by the team number it displays a popup dialog and the link on that popup is not working. Same for the passkey field.
Links inside the popup dialog for the "Learn" option.
Link for "News".
Links inside the "Help" popup.
The link for "Your team, ...." goes to an external private webpage of the team, not sure if thats the intent but it could just go the fah team home page. For one of my teams (Google) that external link is not working.

https://foldingforum.org/viewtopic.php?p=295108#p295108

Moved from https://github.com/FoldingAtHome/fah-issues/issues/1194

**Comment by informatorius** [comment]
Needs updates for foldingathome.org

**Comment by jcoffland** [comment]
I believe these are all fixed.
