### ISSUE TITLE
Question about GPU support

### ISSUE THREAD

**Issue by 2E0PGS** [FoldingAtHome/fah-nacl-client#82]
Does the FAH NACL client  support GPU folding?

Would it also be possible for the NACL UI to display detected hardware it's making use of like the web control does? CPU:3 % GPU:0 % or atleast list the devices like "found 4 cores" so we know what its utilizing.

**Comment by jcoffland** [comment]
No.  It's not possible to access the GPU from NaCl.  It is possible to detect the number of CPUs but that's pretty much it.
